name: SnapQuest
description: "Race against friends in SnapQuest, where challenges meet competition! Snap your way to victory by completing real-world photo tasks faster than your friends, whether indoors or outdoors. Each challenge is a race to capture, share, and conquer. Who will complete the quest first? Get ready for an adventure where every snap counts!"
publish_to: 'none'
version: 1.1.0
environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  appwrite: ^12.0.0
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.6
  logger: ^1.3.0
  appwrite_auth_kit: ^0.10.0
  shared_preferences: ^2.0.18
  audioplayers: ^6.1.0
  camera: ^0.9.4+5
  video_player: ^2.2.6
  swipable_stack: ^2.0.0
  http: ^0.13.5
  intl: ^0.17.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/appIcon.jpg"
  min_sdk_android: 21
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  fonts:
    - family: Icons
      fonts:
       - asset: assets/fonts/Icons.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  assets:
    - assets/audio/effects/wheel_of_fortune.mp3

