name: Dart Fix

on:
  push:  # Trigger on push to any branch
  pull_request:  # Trigger on pull request to any branch

jobs:
  dart-fix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
      - name: Install dependencies
        run: dart pub get
      - name: Run dart fix
        run: dart fix --apply
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "Applied Dart fixes"
          git push
        if: success()
